In [ ]:
!pip install lazypredict

In [ ]:
from lazypredict.Supervised import LazyRegressor, LazyClassifier

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)

In [ ]:
def transform(value):
  categories = [0,0.5,1,2,3]
  differences = [abs(x-value) for x in categories]
  min_index = differences.index(min(differences))
  return str(categories[min_index])

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# read the data
data = pd.read_csv("final_data.csv")

# Creating train test split
y = data['Target']
print(type(y))
X = data.drop(columns=['Target'], axis=1)
y = y.apply(transform)

#Call train_test_split on the data and capture the results
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

<class 'pandas.core.series.Series'>

In [ ]:
classi=LazyClassifier(verbose=0,predictions=True)
models_c,predictions_c=classi.fit(X_train, X_test, y_train, y_test)

100%|██████████| 29/29 [00:10<00:00,  2.65it/s]

In [ ]:
models_c.drop(['ROC AUC','Balanced Accuracy'],axis=1)

                               Accuracy  F1 Score  Time Taken
Model
LinearDiscriminantAnalysis         0.90      0.90        0.10
LGBMClassifier                     0.94      0.94        0.68
BaggingClassifier                  0.94      0.94        0.12
RandomForestClassifier             0.95      0.94        0.45
DecisionTreeClassifier             0.92      0.92        0.04
ExtraTreesClassifier               0.94      0.94        0.43
NearestCentroid                    0.86      0.86        0.05
ExtraTreeClassifier                0.90      0.90        0.03
XGBClassifier                      0.94      0.94        1.47
LogisticRegression                 0.92      0.92        0.38
KNeighborsClassifier               0.85      0.85        0.19
BernoulliNB                        0.79      0.80        0.05
SVC                                0.89      0.89        0.47
Perceptron                         0.84      0.83        0.05
LabelPropagation                   0.83      0.83        0.67
LabelSpreading                     0.83      0.83        1.02
AdaBoostClassifier                 0.65      0.53        0.51
SGDClassifier                      0.85      0.84        0.13
PassiveAggressiveClassifier        0.80      0.80        0.06
CalibratedClassifierCV             0.86      0.83        2.94
LinearSVC                          0.86      0.83        0.77
GaussianNB                         0.27      0.36        0.03
RidgeClassifier                    0.82      0.79        0.05
RidgeClassifierCV                  0.82      0.79        0.10
QuadraticDiscriminantAnalysis      0.43      0.50        0.05
DummyClassifier                    0.47      0.47        0.03

In [ ]:
y.value_counts()

0.5    2393
0      1497
1       176
2        25
3         5
Name: Target, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE
from collections import Counter
# read the data
data = pd.read_csv("final_data.csv")

# Creating train test split
y = data['Target']
#print(type(y))
X = data.drop(columns=['Target'], axis=1)
y = y.apply(transform)

smote = SMOTE(k_neighbors=3)

# fit predictor and target variable
x_smote, y_smote = smote.fit_resample(X, y)

print('Original dataset shape', Counter(y))
print('Resample dataset shape', Counter(y_smote))

Original dataset shape Counter({'0.5': 2393, '0': 1497, '1': 176, '2': 25, '3': 5})
Resample dataset shape Counter({'0.5': 2393, '1': 2393, '2': 2393, '0': 2393, '3': 2393})

In [ ]:
x_smote

       r1iwstat_d  r1fwre_org  r1cdr_mem1  ...  r1prime  r1fverbal  r1cdr_scor1
0            1.00        0.00        0.50  ...     1.00       0.00         0.50
1            1.00        0.00        1.00  ...     0.00       0.00         1.00
2            1.00        0.00        0.50  ...     1.00       0.00         0.50
3            1.00        1.00        2.00  ...     0.00       1.00         2.00
4            1.00        0.00        0.50  ...     1.00       0.00         0.50
...           ...         ...         ...  ...      ...        ...          ...
11960        1.00        0.00        2.44  ...     0.00       0.00         2.44
11961        1.00        4.00        3.00  ...     0.00       4.00         3.00
11962        1.00        2.36        3.00  ...     0.00       2.36         3.00
11963        1.00        0.00        2.12  ...     0.00       0.00         2.12
11964        1.00        0.00        2.05  ...     0.00       0.00         2.05

[11965 rows x 27 columns]

In [ ]:
up_sampled_data = x_smote.copy()
up_sampled_data['Target'] = y_smote 
up_sampled_data.head()

   r1iwstat_d  r1fwre_org  r1cdr_mem1  ...  r1fverbal  r1cdr_scor1  Target
0        1.00        0.00        0.50  ...       0.00         0.50     0.5
1        1.00        0.00        1.00  ...       0.00         1.00       1
2        1.00        0.00        0.50  ...       0.00         0.50     0.5
3        1.00        1.00        2.00  ...       1.00         2.00       2
4        1.00        0.00        0.50  ...       0.00         0.50     0.5

[5 rows x 28 columns]

In [ ]:
up_sampled_data.to_csv("up_sampled_data.csv",index=False)